# Generated by Django 3.2.25 on 2025-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=5)),
                ('phone', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('acc_num', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
