# Generated by Django 3.2.25 on 2025-04-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='acc_num',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bank',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
