# Generated by Django 3.2.25 on 2025-04-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='aadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
